### PR TITLE
Finished assignment

### PR DESCRIPTION
**Pull request by PeleshkoV**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I created an Anagram Checker.
## What did you learn from the changes you have made?
I have practiced in using Python tools: functions, boollean options, case sensitivity etc.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Maybe, it's possible to make Anagram Checker more concise.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Yes, I should have googled next terminology; is case sensitivity, lower, len and sorted functions.
## How were these changes tested?
I tested my Anagram Checker on provided examples. 
## A reference to a related issue in your repository (if applicable)
N/A
## Checklist
- [Y] I can confirm that my changes are working as intended - Yes

### CODE REVIEW

**Review by dwz92 — CHANGES_REQUESTED** [review]
Make sure you are returning `bool` values (eg. `True` or `False`). Right now you are returning a string

**Comment by PeleshkoV** [comment]
Hello! I made changes to my assignment #1 according to your comments. See commit # 2. Thank you.

**Review by dwz92 — APPROVED** [review]
I will approve it since the deadline is near, but please fix your assignment according to the comments I gave on Slack.

**Comment by PeleshkoV** [comment]
Thank you, Emma. I made changes according to your comments #2.

**Review by dwz92 — APPROVED** [review]

**Pull request merged**
